spring.application.name=beospring

# Automatically pick up active profile from environment variable (default to dev if missing)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Optional local .env loading
spring.config.import=optional:file:.env[.properties]

# Server Port
server.port=${PORT:8080}

# Common Datasource Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# NanoId Settings
nanoid.default.length=10
