name: Java CI with Maven

on:
  push:
    branches: [ '**' ] # Triggers action on every push / every branch
  pull_request:
    branches: [ 'main' ] # Triggers on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    # Inject GitHub secrets into environment or fetch with Bitwarden secrets
    env:
      SPRING_PROFILES_ACTIVE: prod

    steps:
      - name: Get secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            26c92fa6-7d2b-4710-8cbe-b4a00180d274 > DB_URL
            42309dce-514e-41bd-bd10-b4a00180e2fa > DB_USERNAME
            621ac999-07ba-4acc-8f16-b4a00180f013 > DB_PASSWORD

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests and Check Coverage
        run: mvn clean verify